/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RaizERisoRouteImport } from './routes/raiz-e-riso'
import { Route as IndexRouteImport } from './routes/index'

const RaizERisoRoute = RaizERisoRouteImport.update({
  id: '/raiz-e-riso',
  path: '/raiz-e-riso',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/raiz-e-riso': typeof RaizERisoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/raiz-e-riso': typeof RaizERisoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/raiz-e-riso': typeof RaizERisoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/raiz-e-riso'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/raiz-e-riso'
  id: '__root__' | '/' | '/raiz-e-riso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RaizERisoRoute: typeof RaizERisoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/raiz-e-riso': {
      id: '/raiz-e-riso'
      path: '/raiz-e-riso'
      fullPath: '/raiz-e-riso'
      preLoaderRoute: typeof RaizERisoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RaizERisoRoute: RaizERisoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
