/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EstadiasRouteImport } from './routes/estadias'
import { Route as MatoAdentroRouteImport } from './routes/mato-adentro'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as RaizERisoRouteImport } from './routes/raiz-e-riso'
import { Route as SaberesDigitaisRouteImport } from './routes/saberes-digitais'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as TerritorioLocalRouteImport } from './routes/territorio-local'
import { Route as ExperienciasPersonalizadasRouteImport } from './routes/experiencias/personalizadas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadiasRoute = EstadiasRouteImport.update({
  id: '/estadias',
  path: '/estadias',
  getParentRoute: () => rootRouteImport,
} as any)
const MatoAdentroRoute = MatoAdentroRouteImport.update({
  id: '/mato-adentro',
  path: '/mato-adentro',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RaizERisoRoute = RaizERisoRouteImport.update({
  id: '/raiz-e-riso',
  path: '/raiz-e-riso',
  getParentRoute: () => rootRouteImport,
} as any)
const SaberesDigitaisRoute = SaberesDigitaisRouteImport.update({
  id: '/saberes-digitais',
  path: '/saberes-digitais',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritorioLocalRoute = TerritorioLocalRouteImport.update({
  id: '/territorio-local',
  path: '/territorio-local',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasPersonalizadasRoute =
  ExperienciasPersonalizadasRouteImport.update({
    id: '/experiencias/personalizadas',
    path: '/experiencias/personalizadas',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/estadias': typeof EstadiasRoute
  '/mato-adentro': typeof MatoAdentroRoute
  '/newsletter': typeof NewsletterRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/raiz-e-riso': typeof RaizERisoRoute
  '/saberes-digitais': typeof SaberesDigitaisRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/territorio-local': typeof TerritorioLocalRoute
  '/experiencias/personalizadas': typeof ExperienciasPersonalizadasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/estadias': typeof EstadiasRoute
  '/mato-adentro': typeof MatoAdentroRoute
  '/newsletter': typeof NewsletterRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/raiz-e-riso': typeof RaizERisoRoute
  '/saberes-digitais': typeof SaberesDigitaisRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/territorio-local': typeof TerritorioLocalRoute
  '/experiencias/personalizadas': typeof ExperienciasPersonalizadasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/estadias': typeof EstadiasRoute
  '/mato-adentro': typeof MatoAdentroRoute
  '/newsletter': typeof NewsletterRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/raiz-e-riso': typeof RaizERisoRoute
  '/saberes-digitais': typeof SaberesDigitaisRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/territorio-local': typeof TerritorioLocalRoute
  '/experiencias/personalizadas': typeof ExperienciasPersonalizadasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contato'
    | '/estadias'
    | '/mato-adentro'
    | '/newsletter'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/raiz-e-riso'
    | '/saberes-digitais'
    | '/sobre'
    | '/termos-de-uso'
    | '/territorio-local'
    | '/experiencias/personalizadas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contato'
    | '/estadias'
    | '/mato-adentro'
    | '/newsletter'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/raiz-e-riso'
    | '/saberes-digitais'
    | '/sobre'
    | '/termos-de-uso'
    | '/territorio-local'
    | '/experiencias/personalizadas'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contato'
    | '/estadias'
    | '/mato-adentro'
    | '/newsletter'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/raiz-e-riso'
    | '/saberes-digitais'
    | '/sobre'
    | '/termos-de-uso'
    | '/territorio-local'
    | '/experiencias/personalizadas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ContatoRoute: typeof ContatoRoute
  EstadiasRoute: typeof EstadiasRoute
  MatoAdentroRoute: typeof MatoAdentroRoute
  NewsletterRoute: typeof NewsletterRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  RaizERisoRoute: typeof RaizERisoRoute
  SaberesDigitaisRoute: typeof SaberesDigitaisRoute
  SobreRoute: typeof SobreRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  TerritorioLocalRoute: typeof TerritorioLocalRoute
  ExperienciasPersonalizadasRoute: typeof ExperienciasPersonalizadasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadias': {
      id: '/estadias'
      path: '/estadias'
      fullPath: '/estadias'
      preLoaderRoute: typeof EstadiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mato-adentro': {
      id: '/mato-adentro'
      path: '/mato-adentro'
      fullPath: '/mato-adentro'
      preLoaderRoute: typeof MatoAdentroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raiz-e-riso': {
      id: '/raiz-e-riso'
      path: '/raiz-e-riso'
      fullPath: '/raiz-e-riso'
      preLoaderRoute: typeof RaizERisoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saberes-digitais': {
      id: '/saberes-digitais'
      path: '/saberes-digitais'
      fullPath: '/saberes-digitais'
      preLoaderRoute: typeof SaberesDigitaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territorio-local': {
      id: '/territorio-local'
      path: '/territorio-local'
      fullPath: '/territorio-local'
      preLoaderRoute: typeof TerritorioLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias/personalizadas': {
      id: '/experiencias/personalizadas'
      path: '/experiencias/personalizadas'
      fullPath: '/experiencias/personalizadas'
      preLoaderRoute: typeof ExperienciasPersonalizadasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ContatoRoute: ContatoRoute,
  EstadiasRoute: EstadiasRoute,
  MatoAdentroRoute: MatoAdentroRoute,
  NewsletterRoute: NewsletterRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  RaizERisoRoute: RaizERisoRoute,
  SaberesDigitaisRoute: SaberesDigitaisRoute,
  SobreRoute: SobreRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  TerritorioLocalRoute: TerritorioLocalRoute,
  ExperienciasPersonalizadasRoute: ExperienciasPersonalizadasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
